SELECT * FROM hr.locations;
SHOW COLUMNS FROM locations;
SHOW COLUMNS FROM regions;
SHOW COLUMNS FROM countries;

-- Exe 1
ALTER TABLE locations CHANGE COLUMN STREET_ADDRESS ADDRESS VARCHAR(40); 

-- Exe 2
ALTER TABLE regions CHANGE COLUMN REGION_NAME REGION VARCHAR(25);

-- Exe 3
ALTER TABLE countries CHANGE COLUMN COUNTRY_NAME COUNTRY VARCHAR(40);
