-- ex 1
SELECT MAX(SALARY) FROM employees;

-- ex 2
SELECT MAX(SALARY) - MIN(SALARY) FROM employees;

-- ex 3
SELECT JOB_ID, AVG(SALARY) AS AVERAGE_SALARY
FROM employees
GROUP BY JOB_ID
ORDER BY AVERAGE_SALARY DESC;

-- ex 4
SELECT SUM(SALARY) AS TOTAL_SALARY FROM employees;

-- ex 5
SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), ROUND(AVG(SALARY),2) FROM employees;

-- ex 6
SELECT COUNT(JOB_ID) FROM employees
WHERE JOB_ID = 'IT_PROG';

-- ex 7
SELECT SUM(SALARY), JOB_ID
FROM employees
GROUP BY JOB_ID;

-- ex 8
SELECT SUM(SALARY), JOB_ID
FROM employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

-- ex 9
SELECT AVG(SALARY), JOB_ID
FROM employees
GROUP BY JOB_ID
HAVING JOB_ID <> 'IT_PROG';

-- ex 10
SELECT AVG(SALARY), COUNT(DEPARTMENT_ID) AS DEPARTAMENTO
FROM employees
GROUP BY DEPARTMENT_ID
HAVING DEPARTAMENTO > 10;

-- ex 11
UPDATE employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';

-- ex 12
SELECT * FROM employees
WHERE LENGTH(FIRST_NAME) >= 8;

-- ex 13
SELECT EMPLOYEE_ID AS id, FIRST_NAME AS 'primeiro nome', YEAR(HIRE_DATE) AS 'ano no qual foi contratado'
FROM employees;

-- ex 14
SELECT EMPLOYEE_ID AS id, FIRST_NAME AS 'primeiro nome', DAY(HIRE_DATE) AS 'dia do mês no qual foi contratado'
FROM employees;

-- ex 15
SELECT EMPLOYEE_ID AS id, FIRST_NAME AS 'primeiro nome', MONTH(HIRE_DATE) AS 'mês no qual foi contratado'
FROM employees;

-- ex 16
SELECT UPPER(CONCAT(FIRST_NAME, ' ', LAST_NAME))
FROM employees;

-- ex 17
SELECT LAST_NAME, HIRE_DATE
FROM employees
WHERE HIRE_DATE LIKE '1987-07%';

-- ex 18
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) 'DAYS'
FROM employees;
